export const exerciseList = [
  { id: '1', name: 'Bench Press' },
  { id: '2', name: 'Squat' },
  { id: '3', name: 'Deadlift' },
  { id: '4', name: 'Bicep Curl' },
  { id: '5', name: 'Tricep Dips' },
  { id: '6', name: 'Shoulder Press' },
  { id: '7', name: 'Lat Pulldown' },
  { id: '8', name: 'Seated Row' },
  { id: '9', name: 'Chest Fly' },
  { id: '10', name: 'Leg Press' },
  { id: '11', name: 'Lunges' },
  { id: '12', name: 'Calf Raise' },
  { id: '13', name: 'Pull-ups' },
  { id: '14', name: 'Dumbbell Rows' },
  { id: '15', name: 'Barbell Rows' },
  { id: '16', name: 'Hammer Curl' },
  { id: '17', name: 'Overhead Tricep Extension' },
  { id: '18', name: 'Incline Bench Press' },
  { id: '19', name: 'Arnold Press' },
  { id: '20', name: 'Plank' },
];
